resolver: lts-10.7
nixpkgs:
  url: https://github.com/NixOS/nixpkgs/archive/d0b24f28fa364ff758f86f2f742f80e0f0e603a2.tar.gz
  sha256: 0hmw0wf4h5aqlzc9ag3xxqr0wcxdaa7p23scbnqixs2b488aj48r

packages:
  s2n-pkg1: ./pkg1
  s2n-pkg2: ./pkg2

extra-deps:
  async: 2.2.1
  base-noprelude: 4.10.1.0
  caps:
    git: https://github.com/int-index/caps.git
    rev: 2f46fc6d5480bdef0a17f64359ad6eb29510dba4
    sha256: 0dz7scllns15d9zbjsgzlp379kcyqzq65qggr2s924skinzz4470
  dependent-sum:
    git: https://github.com/mokus0/dependent-sum.git
    rev: f8909cb323b4ffa63af6c4e7cb3a9745e6199080
    sha256: 0a3ilj6qr4b6abv10l8z1dlllf3aw8ap0ll12zxxm3zqn4n3z2i5
  loot-crypto:
    git: https://github.com/serokell/lootbox.git
    rev: 983b19bd438a47c91184b0b71213e76cc9983b03
    subdir: code/crypto
    sha256: 0wy34066zg8ww2apxv5jlad53r2pcjv88jhww0npn05bck9lyqp2

  loot-prelude:  # required for loot-crypto
    git: https://github.com/serokell/lootbox.git
    rev: 983b19bd438a47c91184b0b71213e76cc9983b03
    subdir: code/prelude
    sha256: 0wy34066zg8ww2apxv5jlad53r2pcjv88jhww0npn05bck9lyqp2
