resolver: lts-10.7

packages:
  - ./pkg1
  - ./pkg2

extra-deps:
  - async-2.2.1
  - base-noprelude-4.10.1.0
  - git: https://github.com/int-index/caps.git
    commit: 2f46fc6d5480bdef0a17f64359ad6eb29510dba4
  - git: https://github.com/mokus0/dependent-sum.git
    commit: f8909cb323b4ffa63af6c4e7cb3a9745e6199080
